// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public class Scenes {
    
    public static string Boot = "Boot";
    
    public static string Title = "Title";
    
    public static string LevelSelection = "LevelSelection";
    
    public static string MapSelection = "MapSelection";
    
    public static string Main = "Main";
}


public class SceneNumbers {
    
    public static int Boot = 0;
    
    public static int Title = 1;
    
    public static int LevelSelection = 2;
    
    public static int MapSelection = 3;
    
    public static int Main = 4;
}


public class Tags {
    
    public static string Untagged = "Untagged";
    
    public static string Respawn = "Respawn";
    
    public static string Finish = "Finish";
    
    public static string EditorOnly = "EditorOnly";
    
    public static string MainCamera = "MainCamera";
    
    public static string Player = "Player";
    
    public static string GameController = "GameController";
    
    public static string SceneController = "SceneController";
    
    public static string Ball = "Ball";
    
    public static string Billboard = "Billboard";
}


public class SortingLayers {
    
    public static string Ground = "Ground";
    
    public static string Panel = "Panel";
    
    public static string FloorEffect = "FloorEffect";
    
    public static string Item = "Item";
    
    public static string FieldEffect = "FieldEffect";
    
    public static string Wall = "Wall";
    
    public static string Barrier = "Barrier";
    
    public static string Default = "Default";
    
    public static string ScreenEffect = "ScreenEffect";
    
    public static string OverScreen = "OverScreen";
}


public class Layers {
    
    public static int Default = 0;
    
    public static int TransparentFX = 1;
    
    public static int IgnoreRaycast = 2;
    
    public static int Water = 4;
    
    public static int UI = 5;
    
    public static int ScreenEffect = 8;
    
    public static int OverScreen = 9;
    
    public static int Ball = 13;
    
    public static int BallContact = 14;
    
    public static int Barrier = 16;
    
    public static int BarrierCore = 17;
    
    public static int BarrierZone = 18;
    
    public static int Ground = 20;
    
    public static int Panel = 21;
    
    public static int Wall = 22;
    
    public static int Item = 23;
    
    public static int Effect = 25;
    
    public static int Space = 30;
}
