// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



[UnityEngine.RequireComponent(typeof(UnityEngine.Animator))]
public class HealingPanelEffectAnimation : UnityEngine.MonoBehaviour {
    
    private UnityEngine.Animator animator;
    
    public bool Healing {
        get {
            return this.animator.GetBool(Hash.Healing);
        }
        set {
            this.animator.SetBool(Hash.Healing, value);
        }
    }
    
    private void Awake() {
        this.animator = this.GetComponent <UnityEngine.Animator>();
    }
    
    private class Name {
        
        public const string Healing = "Healing";
    }
    
    private class Hash {
        
        public static int Healing = UnityEngine.Animator.StringToHash(Name.Healing);
    }
}
